server:
  name: go-sql-layer-architecture-sample
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://postgres:abcd1234@localhost/masterdata?sslmode=disable

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  separate: true
  skips: /health
  request: request
  response: response
  size: size
