server:
  name: go-sql-layer-architecture-sample
  port: 8080

sql:
  driver: postgres
  data_source_name: postgres://xkjofgbu:MKmT3B0PPIZ6pr057wEHFUMvtad5nXex@satao.db.elephantsql.com/xkjofgbu

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  separate: true
  skips: /health
  request: request
  response: response
  size: size
